config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  devise_for :users
  resources :reserves

  root 'reserves#index'
  

end

app/models/reserve.rb
class Reserve < ActiveRecord::Base
end

app/models/room.rb
class Room < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/reserves_controller.rb
class ReservesController < ApplicationController

	def index
	  @room_reserves = Reserve.all
	end

	def new
	  @reserve = Reserve.new
	end

	def create
	  @room = Room.find(params[:room_id])
	  @room_reserve = Reserve.create(user_id: current_user.id, room_id: params[:room_id]) if @room.status == true
	end

	def show
      @room_reserve = Reserve.find(:id)
      @room = Room.find(@room_reserve.room_id)
	end

	def edit
	  @room_reserve = Reserve.find(:id)
      @room = Room.find(@room_reserve.room_id)
	end

	def update
	  @room_reserve = Reserve.find(:id)
      @room = Room.find(@room_reserve.room_id)
      @room.update_attributes(params[:room])
	end

	def destroy
	  @room_reserve = Reserve.find(:id)
	  if @room_reserve.destroy
        @room = Room.find(@room_reserve.room_id)
        @room.update_attributes(from_date: nil, to_date: nil, statu: true)
      end
	end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :status, :from_date, :to_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookmyroom</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
<%= yield %>

</body>
</html>

app/views/reserves/_form.html.erb
<%= form_for(@reserve) do |f| %>
  <% if @reserve.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reserve.errors.count, "error") %> prohibited this reserve from being saved:</h2>

      <ul>
      <% @reserve.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <% rooms = Room.all.where(status: true).pluck(:name) %>
    <%= select_tag(:name, options_for_select(rooms, rooms[0]), :prompt => 'Select') %>
  </div>

  <div class="field">
    <%= f.label :from_date %><br>
    <%= datetime_field_tag :from_date %>
  </div>
  <div class="field">
    <%= f.label :to_date %><br>
    <%= datetime_field_tag :to_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reserves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Room</h1>

<table>
  <thead>
    <tr>
      <th>Room Name</th>
      <th>Status</th>
      <th>From date</th>
      <th>To date</th>
      <th> Reserved By </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @room_reserves .each do |r| %>
      <% room = Room.find(r.room_id) %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.status %></td>
        <td><%= room.from_date %></td>
        <td><%= room.to_date %></td>
        <td><%= User.find(r.user_id).name %>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', r, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Book New Room', new_reserf_path %>

app/views/reserves/new.html.erb
<h1>Book A Room</h1>

<%= render 'form' %>

<%= link_to 'Back', reserves_path %>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.select(:name, Room.all.where(status: true).collect {|u| [u.name, u.id]}, :prompt => 'Select') %>
  </div>

  <div class="field">
    <%= f.label :from_date %><br>
    <%= f.datetime_select :from_date %>
  </div>
  <div class="field">
    <%= f.label :to_date %><br>
    <%= f.datetime_select :to_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th>From date</th>
      <th>To date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.status %></td>
        <td><%= room.from_date %></td>
        <td><%= room.to_date %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @room.status %>
</p>

<p>
  <strong>From date:</strong>
  <%= @room.from_date %>
</p>

<p>
  <strong>To date:</strong>
  <%= @room.to_date %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>